AWSTemplateFormatVersion: 2010-09-09
Description: Example template to test inline Lambda code.
Resources:
  MyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
  TestFunction1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: !Sub
          - |
            def handler(event, context):
                return ${ValueToSub1} + "-" + event["bar"]
          - ValueToSub1: "foo"
      Handler: index.handler
      Role: !GetAtt MyRole.Arn
      Runtime: python3.6
Outputs:
  TestFunction1:
    Value: !Ref TestFunction1
